### PR TITLE
Ct add wh40 gw1100

### PR DESCRIPTION
**Pull request by snoopydooper**
https://github.com/evansunleyjames/homebridge-ecowitt/pulls

### CODE REVIEW

**Comment by Scoo27** [comment]
can you please add GW1100 Support and Node 18 Support @evansunleyjames  ?
Can't see humidity and temperature from my GW1100.

**Comment by evansunleyjames** [comment]
Hi! Like you I only forked this in order to use it with the sensor I had, so I am happy to merge this with the caveat that I won't be testing it at all. Can you fix up the conflicts first though?

**Comment by Scoo27** [comment]
hi,
who do you mean?
how to merge / fix the conflicts? i'm not used to it.

edit @evansunleyjames: 
 ok, clicked something that had to be reviewd. Maybe the problem is fixed.

So how do i get my gw1100 sensors into homebridge?
Does it have anything to do with these ".TS-Files" (eg EcowittPlatform.ts )?

**Comment by Scoo27** [comment]
hi,
who do you mean?
how to merge / fix the conflicts? i'm not used to it. maybe i have no write-access.

**Review by Scoo27 — APPROVED** [review]
comments reviewed.

**Pull request merged**
